version: '3.8'
services:
    php-apache:
        build: .
        depends_on:
            - db
        volumes:
            - /Users/israelcaceres/Documents/alquiler:/var/www/html/
        ports:
            - 8081:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8082:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db        